# Generated by Django 3.2.9 on 2021-12-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('full_name', models.CharField(max_length=300, verbose_name='full name')),
                ('cut_name', models.CharField(max_length=150, verbose_name='cut name')),
                ('inn', models.CharField(max_length=12, verbose_name='INN')),
                ('kpp', models.CharField(max_length=9, verbose_name='KPP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
