# Generated by Django 3.2.9 on 2021-12-06 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20211205_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,12}$'), django.core.validators.MinLengthValidator(10)], verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$'), django.core.validators.MinLengthValidator(9)], verbose_name='KPP'),
        ),
    ]
