# Generated by Django 3.2.9 on 2021-12-03 20:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartamentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binded_at', models.DateTimeField(auto_now_add=True, verbose_name='binded_at')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binds', to='departaments.departament', verbose_name='departament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binds', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='departament',
            name='users',
            field=models.ManyToManyField(related_name='departaments', through='departaments.DepartamentUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
