# Generated by Django 3.2.9 on 2021-12-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20211205_1539'),
        ('departaments', '0002_auto_20211205_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departaments', to='companies.company', verbose_name='company'),
            preserve_default=False,
        ),
    ]
