# Generated by Django 3.2.9 on 2021-12-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0003_departament_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='families',
            field=models.ManyToManyField(blank=True, through='departaments.Family', to='departaments.Departament', verbose_name='families'),
        ),
    ]
