# Generated by Django 3.2.9 on 2021-12-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0004_alter_departament_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='departaments.departament', verbose_name='child'),
        ),
    ]
