# Generated by Django 3.2.9 on 2021-12-06 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departaments', '0006_auto_20211205_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='departaments', through='departaments.DepartamentUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
