# Generated by Django 3.2.9 on 2021-12-05 15:39

import clients.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', clients.models.CustomUserManager()),
            ],
        ),
    ]
